FROM php:8.1-fpm

ENV LIBZIP_CFLAGS \
    LIBZIP_LIBS

RUN apt-get update \
     && apt-get install -y libzip-dev \
     libicu-dev \
     libxslt-dev \
     libpng-dev \
     zlib1g-dev \
     libjpeg-dev \
     libfreetype6-dev \
     build-essential \
     libpcre3 \
     libpcre3-dev \
     zlib1g \
     zlib1g-dev \
     libssl-dev \
     libgd-dev \
     libxml2 \
     libxml2-dev \
     uuid-dev \
     mailutils \
     msmtp \
     procps \
     vim \
     zip \
     wget \
     supervisor \
	&& mkdir -p /var/run/nginx

RUN set -xe \
    && docker-php-ext-configure bcmath --enable-bcmath \
    && docker-php-ext-configure sockets --enable-sockets \
    && docker-php-ext-configure zip \
    && docker-php-ext-configure intl --enable-intl \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql \
    && docker-php-ext-configure xsl \
    && docker-php-ext-configure soap --enable-soap \
    && docker-php-ext-install -j$(nproc) \
        bcmath \
        zip \
        intl \
        pdo_mysql \
        soap \
        xsl \
        sockets \
        opcache

RUN docker-php-ext-configure gd \
    --with-freetype \
    --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-enable gd

RUN pecl install mailparse \
    && docker-php-ext-enable mailparse

RUN apt update -y && \
  apt install git -y \
  apache2-utils

# Configure PHP-FPM
COPY ./docker-config/php/php.ini /usr/local/etc/php/php.ini
COPY ./docker-config/php/msmtprc /etc/msmtprc
COPY ./docker-config/php/www.conf /usr/local/etc/php-fpm.d/www.conf

# RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Install Nginx
RUN cd /opt \
    && wget http://nginx.org/download/nginx-1.20.2.tar.gz \
    && tar -zxvf nginx-1.20.2.tar.gz \
    && cd nginx-1.20.2 && ./configure --prefix=/var/www/html \
    --sbin-path=/usr/sbin/nginx \
    --conf-path=/etc/nginx/nginx.conf \
    --http-log-path=/var/log/nginx/access.log \
    --error-log-path=/var/log/nginx/error.log --with-pcre  \
    --lock-path=/var/lock/nginx.lock \
    --pid-path=/var/run/nginx.pid \
    --with-http_ssl_module \
    --with-http_image_filter_module=dynamic \
    --modules-path=/etc/nginx/modules \
    --with-http_v2_module \
    --with-stream=dynamic \
    --with-http_addition_module \
    --with-http_mp4_module \
    && make \
    && make install

# Configure nginx

# Install NodeJs
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g grunt-cli \
    && npm install grunt --save-dev

# COPY ./docker-config/nginx/app.conf /etc/nginx/conf.d/default.conf
COPY ./docker-config/nginx/app.conf /etc/nginx/nginx.conf

# Configure supervisord
COPY ./docker-config/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# stdout configuration for nginx logs
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

WORKDIR /var/www/html

# COPY . .

# Run sh setup.sh

EXPOSE 9000 80

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]